name: "auto-push-alist"
description: "自动推动目录到 Alist"
# 定义输入参数
inputs:
  token:
    description: "alist的token"
    required: true
  upUrl:
    description: "alist地址"
    required: true
  saveDir:
    description: "alist保存的路径"
    required: true
  upDir:
    description: "本地要上传的目录"
    required: false
  upFile:
    description: "本地要上传的文件"
    required: false
  asTask:
    description: "是否添加为任务"
    required: false
runs:
  # 脚本运行环境（按官方文档给的20版本来使用）
  using: "node20"
  # 脚本执行入口（这里我们要用@vercel/ncc编译）
  main: "dist/index.js"
